Feature/buyer order db
NeighborFood/NeighborFoodAndroid pull request #223
Opened 2022-05-13 01:21 UTC by raedbm

In this feature the buyer can find all of his orders that he made. I connected them to the database so that he can only have a list of his orders. He can find the list of all the orders in the buyerOrdersActivity and their details in BuyerOrdersDetailsActivity.

2022-05-13 01:28 UTC, khalilacheche approved these changes
This implementation is good overall, consitent with the chosen architecture

2022-05-13 01:28 UTC, khalilacheche commented on app/src/main/java/com/epfl/neighborfood/neighborfoodandroid/ui/activities/BuyerOrdersActivity.java
> +public class BuyerOrdersActivity extends AppCompatActivity {
I think this activity should better be named BuyerOrdersList, or something of that sort, to have it more differetiated between the the BuyerOrderDetails

2022-05-13 01:28 UTC, khalilacheche commented on app/src/main/java/com/epfl/neighborfood/neighborfoodandroid/util/Triplet.java
> +public class Triplet<U, V, T>
It's good that you added this in a separate package, this could come in handy for other use cases

2022-05-13 01:32 UTC, khalilacheche commented on app/src/main/java/com/epfl/neighborfood/neighborfoodandroid/models/Order.java
> +        return null;
this has to be modified

2022-05-13 01:32 UTC, khalilacheche commented on app/src/main/java/com/epfl/neighborfood/neighborfoodandroid/models/Order.java
>      private boolean status;
the name of the field should be more explicit, what do you mean by status, processed, in process?

2022-05-13 07:36 UTC, Roilek approved these changes

2022-05-13 07:37 UTC, Roilek requested changes
Does not compile

2022-05-26 23:36 UTC, khalilacheche approved these changes

2022-05-26 23:36 UTC, khalilacheche commented on app/src/main/java/com/epfl/neighborfood/neighborfoodandroid/ui/activities/MealActivity.java
> +            System.out.println(mealId+ "------"+ orderId);
these debug sysouts should be removed

2022-05-26 23:36 UTC, khalilacheche commented on app/src/main/java/com/epfl/neighborfood/neighborfoodandroid/ui/fragments/MealListFragment.java
> +            System.out.println("order----"+orderMealList.get(position).getOrderId());
this also should be removed

2022-05-27 00:07 UTC, Boukhari-Mohamed approved these changes

2022-05-27 03:21 UTC, merged